### ISSUE TITLE
Stylesheet without identifier breaks rendering

### ISSUE THREAD

**Issue by mjiderhamn** [difi/vefa-validator#12]
It seems to me there is a problem with the `no.difi.vefa.validator.Validation.render()` method, caused by the fact that the [production repo](http://vefa.difi.no/validator/repo/) configs have no `identifier` for the `stylesheet`s.

I started off with the "Hello world" example as per the [README.md](https://github.com/difi/vefa-validator/blob/master/README.md) and then added 
```java
    if (validation.isRenderable()) {
      validation.render(System.out);
    }
```
like [in the sample application](https://github.com/difi/vefa-validator/blob/master/validator-web/src/main/java/no/difi/vefa/validator/service/WorkspaceService.java#L81).

Running that on an EHF invoice results in
```java
Exception in thread "main" no.difi.vefa.validator.api.ValidatorException: Unable to borrow presenter object from pool for 'null'.
	at no.difi.vefa.validator.ValidatorInstance.render(ValidatorInstance.java:135)
	at no.difi.vefa.validator.Validation.render(Validation.java:175)
	at no.difi.vefa.validator.Validation.render(Validation.java:157)
	at ...
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.register(GenericKeyedObjectPool.java:1108)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:349)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:279)
	at no.difi.vefa.validator.ValidatorInstance.render(ValidatorInstance.java:131)
	... 3 more
```
which seems to be caused by the fact that the `config-ehf-stylesheet-*.xml` files in [stylesheet](http://vefa.difi.no/validator/repo/ehf-stylesheet-049aa9f6bd0ca4eeb614e88bb545ad7588151a4e.asice) [artifacts](http://vefa.difi.no/validator/repo/ehf-stylesheet-a4e01152881071717d903b5de7fda52c2c520936.asice) do not have an `identifier` attribute.
```xml
        <stylesheet path="stylesheet_ehf_t10/Stylesheet_Full.xsl">
        ...
```
thus the ```no.difi.xsd.vefa.validator._1.StylesheetType.identifier``` that is used as pool key is null.

Seems to me that either the configurations should be updated with an `identifier` attribute, or `no.difi.vefa.validator.ValidatorInstance.render()` should default to the `identifier` of the configuration.

**Comment by klakegg** [comment]
This will be fixed when content in test repository are moved to production repository. This is scheduled to happen October 1st.
