### ISSUE TITLE
Repository not running in Windows - java.lang.StackOverflowError

### ISSUE THREAD

**Issue by OlavEinarsen** [difi/vefa-validator#16]
The error occurs in : 
[CL-T10-R008]-For Mime code in attribute use MIMEMediaType.

**Comment by klakegg** [comment]
I think I need some more information on this.

**Comment by OlavEinarsen** [comment]
log:
10:58:09.811 [http-nio-8084-exec-77] INFO  no.difi.asic.SignatureHelper - C=NO,CN=SMP_2000000105,O=DIFI
10:58:09.818 [http-nio-8084-exec-77] INFO  no.difi.asic.AbstractAsicReader - Found file: META-INF/manifest.xml
10:58:09.821 [http-nio-8084-exec-77] INFO  n.d.v.v.s.AbstractSourceInstance - Signature: C=NO,CN=SMP_2000000105,O=DIFI
10:58:09.931 [http-nio-8084-exec-77] INFO  n.d.vefa.validator.ValidatorEngine - Loaded: EHF Catalogue 1.0.2
10:58:09.931 [http-nio-8084-exec-77] INFO  n.d.vefa.validator.ValidatorEngine - Loaded: EHF Despatch Advice 1.0.1
10:58:09.931 [http-nio-8084-exec-77] INFO  n.d.vefa.validator.ValidatorEngine - Loaded: EHF Invoice and Creditnote 2.0.4
10:58:09.931 [http-nio-8084-exec-77] INFO  n.d.vefa.validator.ValidatorEngine - Loaded: EHF Ordering 1.0.2
10:58:09.931 [http-nio-8084-exec-77] INFO  n.d.vefa.validator.ValidatorEngine - Loaded: EHF Reminder 1.1.0
10:58:10.015 [http-nio-8084-exec-77] DEBUG no.difi.vefa.validator.Validation - Validate: /work/ubl21-d6122e53220eb8e2732ef0d0c7474b21.asice#maindoc/UBL-Invoice-2.1.xsd
10:58:10.026 [http-nio-8084-exec-77] DEBUG n.d.v.validator.CheckerPoolFactory - Creating checker '/work/ubl21-d6122e53220eb8e2732ef0d0c7474b21.asice#maindoc/UBL-Invoice-2.1.xsd'
10:58:11.848 [http-nio-8084-exec-77] DEBUG no.difi.vefa.validator.Validation - Validate: /work/ehf-f7a436f0223418393b87318ee6d40ddba315f986.asice#xsl/UBL-T10-BiiRules.xsl
10:58:11.848 [http-nio-8084-exec-77] DEBUG n.d.v.validator.CheckerPoolFactory - Creating checker '/work/ehf-f7a436f0223418393b87318ee6d40ddba315f986.asice#xsl/UBL-T10-BiiRules.xsl'
27-Sep-2015 10:59:30.381 SEVERE [http-nio-8084-exec-77] com.sun.xml.ws.server.sei.TieHandler.createResponse null
 java.lang.StackOverflowError
	at java.util.Stack.push(Stack.java:67)
	at net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:184)
	at net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	at net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	at net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	at net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	at net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	at net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	at net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	at net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	at net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	at net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	at net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	at net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	at net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	at net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	at net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	at net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)

**Comment by OlavEinarsen** [comment]
i supppose this issue occures when the choose test contains more then 256 elements.
[CL-T10-R008] rule contains 917 diferent elements.

i have been abel to eliminate the issue bye becrease counts of elements in test by adding more when statements only holding +-150 elements.

**Comment by rdineshrs** [comment]
javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
</pre></p><p><b>root cause</b> <pre>java.lang.StackOverflowError
	java.util.Stack.push(Stack.java:67)
	net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:184)
	net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)
	net.sf.saxon.expr.BooleanExpression.typeCheck(BooleanExpression.java:55)
	net.sf.saxon.expr.parser.ExpressionVisitor.typeCheck(ExpressionVisitor.java:188)
	net.sf.saxon.expr.BinaryExpression.typeCheck(BinaryExpression.java:55)

**Comment by m4caron** [comment]
Have you tried increasing stack size with -Xss parameter?

https://blogs.oracle.com/saas-fusion-app-performance/entry/how_set_stack_size_to

**Comment by rdineshrs** [comment]
Thanks. Worked for me.
i just set the stack size to -Xss4m.
