### ISSUE TITLE
ValidatorBuilder.build throws ExceptionInInitializerError when processing asicmanifest.xml

### ISSUE THREAD

**Issue by thierryvt** [difi/vefa-validator#40]
Title says it, when I try to build the validator the program crashes.

Code used (I downloaded the necessary artifacts to a local directory):                       

    ValidatorBuilder builder = ValidatorBuilder.newValidator();
    builder.setSource(new RepositorySource(new File("D:\\workspace\\validator_artifacts").toURI()));			
    validator = builder.build();

as soon as "builder.build" is run the following excecption is thrown:

    Exception in thread "main" java.lang.ExceptionInInitializerError
        at no.difi.asic.AbstractAsicReader.handleMetadataEntry(AbstractAsicReader.java:146)
        at no.difi.asic.AbstractAsicReader.getNextFile(AbstractAsicReader.java:75)
        at no.difi.asic.AsicReader.getNextFile(AsicReader.java:21)
        at no.difi.vefa.validator.source.AbstractSourceInstance.unpackContainer(AbstractSourceInstance.java:71)
        at no.difi.vefa.validator.source.RepositorySourceInstance.<init>(RepositorySourceInstance.java:32)
        at no.difi.vefa.validator.source.RepositorySource.createInstance(RepositorySource.java:48)
        at no.difi.vefa.validator.ValidatorInstance.<init>(ValidatorInstance.java:72)
        at no.difi.vefa.validator.Validator.load(Validator.java:126)
        at no.difi.vefa.validator.ValidatorBuilder.build(ValidatorBuilder.java:188)
        at eu.sendregning.oxalis.Main.main(Main.java:51)
    Caused by: java.lang.IllegalStateException: Unable to create JAXBContext: 22 counts of IllegalAnnotationExceptions
        at no.difi.asic.CadesAsicManifest.<clinit>(CadesAsicManifest.java:28)
        ... 10 more
    Caused by: com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 22 counts of IllegalAnnotationExceptions
    Two classes have the same XML type name "{http://www.w3.org/2000/09/xmldsig#}DigestMethodType". Use @XmlType.name and @XmlType.namespace to assign different names to them.
        this problem is related to the following location:
                at org.w3._2000._09.xmldsig_.DigestMethodType
                at protected org.w3._2000._09.xmldsig_.DigestMethodType org.w3._2000._09.xmldsig_.ReferenceType.digestMethod
                at org.w3._2000._09.xmldsig_.ReferenceType
                at protected java.util.List org.w3._2000._09.xmldsig_.SignedInfoType.reference
                at org.w3._2000._09.xmldsig_.SignedInfoType
                at protected org.w3._2000._09.xmldsig_.SignedInfoType org.w3._2000._09.xmldsig_.SignatureType.signedInfo
                at org.w3._2000._09.xmldsig_.SignatureType
                at public javax.xml.bind.JAXBElement org.w3._2000._09.xmldsig_.ObjectFactory.createSignature(org.w3._2000._09.xmldsig_.SignatureType)
                at org.w3._2000._09.xmldsig_.ObjectFactory
                at protected java.util.List org.w3._2000._09.xmldsig_.DigestMethod.content
                at org.w3._2000._09.xmldsig_.DigestMethod
                at protected org.w3._2000._09.xmldsig_.DigestMethod org.etsi.uri._02918.v1_2.DataObjectReference.digestMethod
                at org.etsi.uri._02918.v1_2.DataObjectReference
                at protected java.util.List org.etsi.uri._02918.v1_2.ASiCManifest.dataObjectReferences
                at org.etsi.uri._02918.v1_2.ASiCManifest
        this problem is related to the following location:

left out a big part of repeating the same "two classes have the same xml type name" errors. (that and the part below it repeat 10 times or so)
Followed by about 10 of these

    There's no ObjectFactory with an @XmlElementDecl for the element {http://www.w3.org/2000/09/xmldsig#}HMACOutputLength.
        this problem is related to the following location:
                at protected java.util.List org.w3._2000._09.xmldsig_.SignatureMethod.content
                at org.w3._2000._09.xmldsig_.SignatureMethod
                at protected org.w3._2000._09.xmldsig_.SignatureMethod org.w3._2000._09.xmldsig_.SignedInfo.signatureMethod
                at org.w3._2000._09.xmldsig_.SignedInfo
                at protected org.w3._2000._09.xmldsig_.SignedInfo org.w3._2000._09.xmldsig_.Signature.signedInfo
                at org.w3._2000._09.xmldsig_.Signature
                at protected java.util.List org.etsi.uri._02918.v1_2.XAdESSignatures.signatures
                at org.etsi.uri._02918.v1_2.XAdESSignatures
                at public org.etsi.uri._02918.v1_2.XAdESSignatures org.etsi.uri._02918.v1_2.ObjectFactory.createXAdESSignatures()
                at org.etsi.uri._02918.v1_2.ObjectFactory
                at protected java.util.List org.etsi.uri._02918.v1_2.AnyType.content
                at org.etsi.uri._02918.v1_2.AnyType
                at org.etsi.uri._02918.v1_2.Extension
                at protected java.util.List org.etsi.uri._02918.v1_2.ExtensionsListType.extensions
                at org.etsi.uri._02918.v1_2.ExtensionsListType
                at protected org.etsi.uri._02918.v1_2.ExtensionsListType org.etsi.uri._02918.v1_2.DataObjectReference.dataObjectReferenceExtensions
                at org.etsi.uri._02918.v1_2.DataObjectReference
                at protected java.util.List org.etsi.uri._02918.v1_2.ASiCManifest.dataObjectReferences
                at org.etsi.uri._02918.v1_2.ASiCManifest

And finally ending with

    at com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException$Builder.check(Unknown Source)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(Unknown Source)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.<init>(Unknown Source)
        at com.sun.xml.internal.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(Unknown Source)
        at com.sun.xml.internal.bind.v2.ContextFactory.createContext(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
        at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
        at javax.xml.bind.ContextFinder.find(Unknown Source)
        at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
        at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
        at no.difi.asic.CadesAsicManifest.<clinit>(CadesAsicManifest.java:26)
        ... 10 more

I don't really enjoy the idea of having to do major changes in the sourcecode of the validator/asic parser projects so I'm hoping it's just a setting I'm missing.

Any help is appreciated.

**Comment by thierryvt** [comment]
[log.txt](https://github.com/difi/vefa-validator/files/701112/log.txt)

added complete log if you need it

**Comment by ftonik** [comment]
I have a similar problem. But the construction of the validator throws an exception when parsing certificate in ehf-stylesheet-9c9a4c4944c4857fa0f45af76bc3aa59c95f551a.asice
I added:

`  compile ('no.difi.vefa:validator-core:2.0.2')`

And then I'm try create validator

`Validator validator = ValidatorBuilder.newValidator().build()`

It's throwed:

`2017-01-13 10:44:06,078 [quartzScheduler_Worker-4] INFO  (grails.app.jobs.NodeActivatorJob) - *** Amount of Nodes to execute 1 ***
2017-01-13 10:44:08,251 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.vefa.validator.source.RepositorySourceInstance) - Fetching https://vefa.difi.no/validator/repo/artifacts.xml
2017-01-13 10:44:09,078 [quartzScheduler_Worker-5] INFO  (grails.app.jobs.NodeActivatorJob) - *** Amount of Nodes to execute 1 ***
2017-01-13 10:44:12,078 [quartzScheduler_Worker-7] INFO  (grails.app.jobs.NodeActivatorJob) - *** Amount of Nodes to execute 1 ***
2017-01-13 10:44:12,902 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.vefa.validator.source.RepositorySourceInstance) - Fetching https://vefa.difi.no/validator/repo/ehf-stylesheet-9c9a4c4944c4857fa0f45af76bc3aa59c95f551a.asice
2017-01-13 10:44:13,080 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.asic.AbstractAsicReader) - Found file: stylesheet_ehf_t10/Stylesheet_Full.xsl
2017-01-13 10:44:13,192 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.asic.AbstractAsicReader) - Found file: stylesheet_ehf_t10/CommonTemplates.xsl
2017-01-13 10:44:13,204 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.asic.AbstractAsicReader) - Found file: stylesheet_ehf_t10/Headlines.xml
2017-01-13 10:44:13,205 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.asic.AbstractAsicReader) - Found file: stylesheet_ehf_t10/PEPPOL.css
2017-01-13 10:44:13,206 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.asic.AbstractAsicReader) - Found file: config-ehf-stylesheet-9c9a4c4944c4857fa0f45af76bc3aa59c95f551a.xml
2017-01-13 10:44:13,206 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.asic.AbstractAsicReader) - Found file: META-INF/asicmanifest.xml
2017-01-13 10:44:13,939 [#45(SupplierWorkflow)-importConversion] INFO  (no.difi.asic.AbstractAsicReader) - Found file: META-INF/signature-2a6ab53e-49d8-4154-967b-f38a05c34cec.p7s
2017-01-13 10:44:14,035 [quartzScheduler_Worker-2] ERROR (grails.app.services.ProcessManagerService) - Node execution throwed exception
java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ProcessManagerService.executeNode(ProcessManagerService.groovy:1249)
	at ProcessManagerService$_invokeNodeExecution_closure11.doCall(ProcessManagerService.groovy:764)
	at ThreadRuntimeInfoService.invokeInCurrentThread(ThreadRuntimeInfoService.groovy:75)
	at ProcessManagerService.invokeNodeExecution(ProcessManagerService.groovy:659)
	at SendEventJob.execute(SendEventJob.groovy:36)
	at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:102)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.ExceptionInInitializerError
	at no.difi.asic.SignatureHelper.<clinit>(SignatureHelper.java:43)
	at no.difi.asic.AbstractAsicReader.handleCadesSigning(AbstractAsicReader.java:169)
	at no.difi.asic.AbstractAsicReader.handleMetadataEntry(AbstractAsicReader.java:153)
	at no.difi.asic.AbstractAsicReader.getNextFile(AbstractAsicReader.java:75)
	at no.difi.asic.AsicReader.getNextFile(AsicReader.java:21)
	at no.difi.vefa.validator.source.AbstractSourceInstance.unpackContainer(AbstractSourceInstance.java:71)
	at no.difi.vefa.validator.source.RepositorySourceInstance.<init>(RepositorySourceInstance.java:32)
	at no.difi.vefa.validator.source.RepositorySource.createInstance(RepositorySource.java:48)
	at no.difi.vefa.validator.ValidatorInstance.<init>(ValidatorInstance.java:72)
	at no.difi.vefa.validator.Validator.load(Validator.java:126)
	at no.difi.vefa.validator.ValidatorBuilder.build(ValidatorBuilder.java:188)
	at Importer.executeImport(Importer:60)
	at com.jcatalog.conversion.importer.ImportService.executeImport(ImportService.groovy:77)
	at com.jcatalog.ssm.grailsflow.actions.BaseHLAction.executeImport(BaseHLAction.groovy:316)
	at conversion.ImportConversionHLAction.service(ImportConversionHLAction.groovy:112)
	at com.jcatalog.ssm.grailsflow.actions.BaseHLAction.doExecute(BaseHLAction.groovy:196)
	at com.jcatalog.ssm.grailsflow.actions.SecurityContextInitializeAction.execute(SecurityContextInitializeAction.groovy:35)
	at com.jcatalog.grailsflow.engine.execution.NodeExecutionHelper.invokeProcessMethod(NodeExecutionHelper.groovy:90)
	at com.jcatalog.grailsflow.engine.execution.NodeExecutor$_execute_closure1.doCall(NodeExecutor.groovy:56)
	at SupplierWorkflowProcess$_closure4_closure8_closure34.doCall(processSupplierWorkflow.groovy:280)
	at com.jcatalog.grailsflow.engine.execution.NodeExecutor$_execute_closure1.doCall(NodeExecutor.groovy:54)
	at com.jcatalog.grailsflow.engine.execution.NodeExecutor$_execute_closure1.doCall(NodeExecutor.groovy:54)
	at com.jcatalog.grailsflow.engine.execution.NodeExecutor.execute(NodeExecutor.groovy:87)
	at ProcessManagerService$_executeNode_closure31_closure52.doCall(ProcessManagerService.groovy:1280)
	at com.jcatalog.grailsflow.logging.LogUtils.redirectLogging(LogUtils.groovy:32)
	at ProcessManagerService$_executeNode_closure31.doCall(ProcessManagerService.groovy:1275)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.SecurityException: class "org.bouncycastle.asn1.ASN1ObjectIdentifier"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at org.codehaus.groovy.tools.RootLoader.oldFindClass(RootLoader.java:171)
	at org.codehaus.groovy.tools.RootLoader.loadClass(RootLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 30 more`

**Comment by ftonik** [comment]
I think that you have some problems with ResourceRepository. If you have Internet connection on develop PC try remove:

`builder.setSource(new RepositorySource(new File("D:\\workspace\\validator_artifacts").toURI()));`

and run again. Artifacts will downloaded from remote server. And all be OK. 
To use locally artifacts downloaded from server I write:

`            Path path = Paths.get("d:/downloads/Production"); `
`            DirectorySource source = new DirectorySource(path)`
`            Validator validator = ValidatorBuilder.newValidator().setSource(source).build()`
 `           Validation validation = validator.validate(<any file>)`
  `          def report = validation.getReport()`

**Comment by thierryvt** [comment]
Bot running it without settings the source and the way you paste it there produce the same set of exceptions.

this is how I run it now:

    Path path = Paths.get("D:/peppol-workspace/validator_artifacts");
    DirectorySource source = new DirectorySource(path);
    Validator validator = ValidatorBuilder.newValidator().setSource(source).build();

Leaving the "setSource" out of it makes no difference, it's always the "build" method that throws the exception.
The last line that outputs (before stacktraces) is always:

2017-01-24 14:31:18,818 INFO [no.difi.asic.AbstractAsicReader] Found file: META-INF/asicmanifest.xml

So might there be an issue with reading the asicmanifest.xml?
[log.txt](https://github.com/difi/vefa-validator/files/726801/log.txt)


Log once more attached should you want to take a look at it.
