### ISSUE TITLE
Guice configuration errors

### ISSUE THREAD

**Issue by runholen** [difi/vefa-validator#49]
When building the latest version, I get the following errors when trying to run it:

`
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for java.util.List<no.difi.vefa.validator.api.Declaration> was bound.
  while locating java.util.List<no.difi.vefa.validator.api.Declaration>
    for the 1st parameter of no.difi.vefa.validator.util.DeclarationDetector.<init>(DeclarationDetector.java:23)
  while locating no.difi.vefa.validator.util.DeclarationDetector
    for field at no.difi.vefa.validator.ValidatorInstance.declarationDetector(ValidatorInstance.java:29)
  while locating no.difi.vefa.validator.ValidatorInstance
    for field at no.difi.vefa.validator.Validator.validatorInstance(Validator.java:119)
  while locating no.difi.vefa.validator.Validator

2) No implementation for java.util.List<no.difi.vefa.validator.api.Trigger> was bound.
  while locating java.util.List<no.difi.vefa.validator.api.Trigger>
    for the 1st parameter of no.difi.vefa.validator.trigger.TriggerFactory.<init>(TriggerFactory.java:21)
  while locating no.difi.vefa.validator.trigger.TriggerFactory
    for field at no.difi.vefa.validator.ValidatorInstance.triggerFactory(ValidatorInstance.java:29)
  while locating no.difi.vefa.validator.ValidatorInstance
    for field at no.difi.vefa.validator.Validator.validatorInstance(Validator.java:119)
  while locating no.difi.vefa.validator.Validator

3) No implementation for java.util.List<no.difi.xsd.vefa.validator._1.Configurations> was bound.
  while locating java.util.List<no.difi.xsd.vefa.validator._1.Configurations>
    for the 2nd parameter of no.difi.vefa.validator.ValidatorEngine.<init>(ValidatorEngine.java:62)
  while locating no.difi.vefa.validator.ValidatorEngine
    for field at no.difi.vefa.validator.ValidatorInstance.validatorEngine(ValidatorInstance.java:29)
  while locating no.difi.vefa.validator.ValidatorInstance
    for field at no.difi.vefa.validator.Validator.validatorInstance(Validator.java:119)
  while locating no.difi.vefa.validator.Validator

4) No implementation for com.google.common.cache.LoadingCache<java.lang.String, no.difi.vefa.validator.api.Checker> was bound.
  while locating com.google.common.cache.LoadingCache<java.lang.String, no.difi.vefa.validator.api.Checker>
    for field at no.difi.vefa.validator.ValidatorInstance.checkerCache(ValidatorInstance.java:29)
  while locating no.difi.vefa.validator.ValidatorInstance
    for field at no.difi.vefa.validator.Validator.validatorInstance(Validator.java:119)
  while locating no.difi.vefa.validator.Validator

5) No implementation for com.google.common.cache.LoadingCache<java.lang.String, no.difi.vefa.validator.api.Renderer> was bound.
  while locating com.google.common.cache.LoadingCache<java.lang.String, no.difi.vefa.validator.api.Renderer>
    for field at no.difi.vefa.validator.ValidatorInstance.rendererCache(ValidatorInstance.java:29)
  while locating no.difi.vefa.validator.ValidatorInstance
    for field at no.difi.vefa.validator.Validator.validatorInstance(Validator.java:119)
  while locating no.difi.vefa.validator.Validator

5 errors
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1075)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1034)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
	at no.difi.vefa.validator.ValidatorBuilder.build(ValidatorBuilder.java:69)
	at Test.main(Test.java:27)
`

**Comment by runholen** [comment]
I finally made some progress with this. Althought I still get all these guice-errors when I try to run eg Cli.java in validator-tester in eclipse, I discovered that running the maven-generated jar-file in target\validator-tester.jar outside of eclipse did not produce them. So I was able to modify the code to include my asice-files for ehf3.0-validation, rebuild with maven, and then use the validator-tester.jar in my other project, and the validation seems to work :-)
